/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiDashboardRouteImport } from './routes/ai-dashboard'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as DataIntelligenceRouteImport } from './routes/data-intelligence'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as InvestmentHistoryRouteImport } from './routes/investment-history'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as OwnershipRouteImport } from './routes/ownership'
import { Route as CompaniesIndexRouteImport } from './routes/companies.index'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies.$companyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDashboardRoute = AiDashboardRouteImport.update({
  id: '/ai-dashboard',
  path: '/ai-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIntelligenceRoute = DataIntelligenceRouteImport.update({
  id: '/data-intelligence',
  path: '/data-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentHistoryRoute = InvestmentHistoryRouteImport.update({
  id: '/investment-history',
  path: '/investment-history',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnershipRoute = OwnershipRouteImport.update({
  id: '/ownership',
  path: '/ownership',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesIndexRoute = CompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/companies/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-dashboard': typeof AiDashboardRoute
  '/alerts': typeof AlertsRoute
  '/data-intelligence': typeof DataIntelligenceRoute
  '/entities': typeof EntitiesRoute
  '/investment-history': typeof InvestmentHistoryRoute
  '/monitoring': typeof MonitoringRoute
  '/ownership': typeof OwnershipRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/': typeof CompaniesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-dashboard': typeof AiDashboardRoute
  '/alerts': typeof AlertsRoute
  '/data-intelligence': typeof DataIntelligenceRoute
  '/entities': typeof EntitiesRoute
  '/investment-history': typeof InvestmentHistoryRoute
  '/monitoring': typeof MonitoringRoute
  '/ownership': typeof OwnershipRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies': typeof CompaniesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-dashboard': typeof AiDashboardRoute
  '/alerts': typeof AlertsRoute
  '/data-intelligence': typeof DataIntelligenceRoute
  '/entities': typeof EntitiesRoute
  '/investment-history': typeof InvestmentHistoryRoute
  '/monitoring': typeof MonitoringRoute
  '/ownership': typeof OwnershipRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/': typeof CompaniesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-dashboard'
    | '/alerts'
    | '/data-intelligence'
    | '/entities'
    | '/investment-history'
    | '/monitoring'
    | '/ownership'
    | '/companies/$companyId'
    | '/companies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-dashboard'
    | '/alerts'
    | '/data-intelligence'
    | '/entities'
    | '/investment-history'
    | '/monitoring'
    | '/ownership'
    | '/companies/$companyId'
    | '/companies'
  id:
    | '__root__'
    | '/'
    | '/ai-dashboard'
    | '/alerts'
    | '/data-intelligence'
    | '/entities'
    | '/investment-history'
    | '/monitoring'
    | '/ownership'
    | '/companies/$companyId'
    | '/companies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiDashboardRoute: typeof AiDashboardRoute
  AlertsRoute: typeof AlertsRoute
  DataIntelligenceRoute: typeof DataIntelligenceRoute
  EntitiesRoute: typeof EntitiesRoute
  InvestmentHistoryRoute: typeof InvestmentHistoryRoute
  MonitoringRoute: typeof MonitoringRoute
  OwnershipRoute: typeof OwnershipRoute
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
  CompaniesIndexRoute: typeof CompaniesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-dashboard': {
      id: '/ai-dashboard'
      path: '/ai-dashboard'
      fullPath: '/ai-dashboard'
      preLoaderRoute: typeof AiDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-intelligence': {
      id: '/data-intelligence'
      path: '/data-intelligence'
      fullPath: '/data-intelligence'
      preLoaderRoute: typeof DataIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment-history': {
      id: '/investment-history'
      path: '/investment-history'
      fullPath: '/investment-history'
      preLoaderRoute: typeof InvestmentHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ownership': {
      id: '/ownership'
      path: '/ownership'
      fullPath: '/ownership'
      preLoaderRoute: typeof OwnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/': {
      id: '/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof CompaniesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiDashboardRoute: AiDashboardRoute,
  AlertsRoute: AlertsRoute,
  DataIntelligenceRoute: DataIntelligenceRoute,
  EntitiesRoute: EntitiesRoute,
  InvestmentHistoryRoute: InvestmentHistoryRoute,
  MonitoringRoute: MonitoringRoute,
  OwnershipRoute: OwnershipRoute,
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
  CompaniesIndexRoute: CompaniesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
